package model;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Apr 06 18:51:56 CST 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for AsesorView1.
     * @return AsesorView1
     */
    public ViewObjectImpl getAsesorView1() {
        return (ViewObjectImpl) findViewObject("AsesorView1");
    }

    /**
     * Container's getter for ClienteView1.
     * @return ClienteView1
     */
    public ViewObjectImpl getClienteView1() {
        return (ViewObjectImpl) findViewObject("ClienteView1");
    }

    /**
     * Container's getter for CuentaView1.
     * @return CuentaView1
     */
    public ViewObjectImpl getCuentaView1() {
        return (ViewObjectImpl) findViewObject("CuentaView1");
    }

    /**
     * Container's getter for EmpleadoView1.
     * @return EmpleadoView1
     */
    public ViewObjectImpl getEmpleadoView1() {
        return (ViewObjectImpl) findViewObject("EmpleadoView1");
    }

    /**
     * Container's getter for PagoView1.
     * @return PagoView1
     */
    public ViewObjectImpl getPagoView1() {
        return (ViewObjectImpl) findViewObject("PagoView1");
    }

    /**
     * Container's getter for PrestamoView1.
     * @return PrestamoView1
     */
    public ViewObjectImpl getPrestamoView1() {
        return (ViewObjectImpl) findViewObject("PrestamoView1");
    }

    /**
     * Container's getter for SucursalView1.
     * @return SucursalView1
     */
    public ViewObjectImpl getSucursalView1() {
        return (ViewObjectImpl) findViewObject("SucursalView1");
    }

    /**
     * Container's getter for SucursualView1.
     * @return SucursualView1
     */
    public ViewObjectImpl getSucursualView1() {
        return (ViewObjectImpl) findViewObject("SucursualView1");
    }

    /**
     * Container's getter for AsesorView2.
     * @return AsesorView2
     */
    public ViewObjectImpl getAsesorView2() {
        return (ViewObjectImpl) findViewObject("AsesorView2");
    }

    /**
     * Container's getter for CuentaView2.
     * @return CuentaView2
     */
    public ViewObjectImpl getCuentaView2() {
        return (ViewObjectImpl) findViewObject("CuentaView2");
    }

    /**
     * Container's getter for AsesorView3.
     * @return AsesorView3
     */
    public ViewObjectImpl getAsesorView3() {
        return (ViewObjectImpl) findViewObject("AsesorView3");
    }

    /**
     * Container's getter for PagoView2.
     * @return PagoView2
     */
    public ViewObjectImpl getPagoView2() {
        return (ViewObjectImpl) findViewObject("PagoView2");
    }

    /**
     * Container's getter for PrestamoView2.
     * @return PrestamoView2
     */
    public ViewObjectImpl getPrestamoView2() {
        return (ViewObjectImpl) findViewObject("PrestamoView2");
    }

    /**
     * Container's getter for PrestamoView3.
     * @return PrestamoView3
     */
    public ViewObjectImpl getPrestamoView3() {
        return (ViewObjectImpl) findViewObject("PrestamoView3");
    }

    /**
     * Container's getter for AsesorCuentaFkLink1.
     * @return AsesorCuentaFkLink1
     */
    public ViewLinkImpl getAsesorCuentaFkLink1() {
        return (ViewLinkImpl) findViewLink("AsesorCuentaFkLink1");
    }

    /**
     * Container's getter for CuentaClienteFkLink1.
     * @return CuentaClienteFkLink1
     */
    public ViewLinkImpl getCuentaClienteFkLink1() {
        return (ViewLinkImpl) findViewLink("CuentaClienteFkLink1");
    }

    /**
     * Container's getter for AsesorEmpleadoFkLink1.
     * @return AsesorEmpleadoFkLink1
     */
    public ViewLinkImpl getAsesorEmpleadoFkLink1() {
        return (ViewLinkImpl) findViewLink("AsesorEmpleadoFkLink1");
    }

    /**
     * Container's getter for PagoPrestamoFkLink1.
     * @return PagoPrestamoFkLink1
     */
    public ViewLinkImpl getPagoPrestamoFkLink1() {
        return (ViewLinkImpl) findViewLink("PagoPrestamoFkLink1");
    }

    /**
     * Container's getter for PrestamoClienteFkLink1.
     * @return PrestamoClienteFkLink1
     */
    public ViewLinkImpl getPrestamoClienteFkLink1() {
        return (ViewLinkImpl) findViewLink("PrestamoClienteFkLink1");
    }

    /**
     * Container's getter for PrestamoSucursualFkLink1.
     * @return PrestamoSucursualFkLink1
     */
    public ViewLinkImpl getPrestamoSucursualFkLink1() {
        return (ViewLinkImpl) findViewLink("PrestamoSucursualFkLink1");
    }
}

